apiVersion: v1
kind: Service
metadata:
  name: hello-visitor-service
  namespace: staging
spec:
  selector:
    app.kubernetes.io/name: hello-visitor
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 8888
    targetPort: 8888