apiVersion: v1
kind: Service
metadata:
  name: hello-visitor-service
  namespace: staging
spec:
  selector:
    app: hello-visitor
  ports:
  - port: 8888
    targetPort: 8888
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: hello-visitor-service
  namespace: production
spec:
  type: NodePort
  selector:
    app: hello-visitor
  ports:
  - port: 8888
    targetPort: 8888
    nodePort: 30001
    protocol: TCP