# apiVersion: networking.k8s.io/v1beta1 # for k3s < v1.19
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-service
            port:
              number: 80
  - http:
      paths:
      - path: /hello
        pathType: Prefix
        backend:
          service:
            name: hello-visitor-service
            port:
              number: 8888
      - path: /hello-staging
        pathType: Prefix
        backend:
          service:
            name: hello-visitor-service
            port:
              number: 8888